
DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers(
id INT NOT NULL AUTO_INCREMENT, 
burger_name VARCHAR(255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT false,
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)






